#!/usr/bin/env bash
# Rebuild a policy baseline we can actually stand behind.
#
# M2's 85.7% is withdrawn (README, ledger L11): five explanations tested and
# killed, and the leading one is untestable because the training data is gone.
# Archaeology on a deleted dataset is not worth more compute. This establishes
# a fresh number instead, with every input recorded.
#
# What is different this time:
#
#   * the dataset is regenerated by a COMMITTED command with a fixed seed, and
#     a manifest recording env commit, episode count and settings goes next to
#     it. L11's lesson is that a number whose inputs are gone is an anecdote.
#   * the leak check must PASS, not be skipped. Last time it reported
#     "SKIPPED (training data not found)" and nobody noticed.
#   * three seeds, all 100 eval seeds, at eval_policy's own default budget.
#
# The frame-stacking arm tests whether the policy is capacity-limited or
# information-limited. A single frame carries no visual motion; proprioception
# supplies joint velocity but nothing says how the SCENE is moving. If stacking
# lifts the number, the policy was starved of information rather than of
# parameters -- which is worth knowing before adding capacity.
set -uo pipefail
cd "$(dirname "$0")/.."

EPISODES=${1:-400}
SEEDS=${2:-"0 1 2"}
DATA=data/episodes/reach_v2
mkdir -p logs checkpoints/m2v2

# ---- 1. collect, reproducibly -------------------------------------------
have=$(ls "$DATA"/episode_*.npz 2>/dev/null | wc -l)
if [ "$have" -ge "$EPISODES" ]; then
    echo "### $DATA: $have episodes, complete"
else
    [ "$have" -gt 0 ] && { echo "### partial ($have), rebuilding"; rm -rf "$DATA"; }
    echo "### collecting $EPISODES reach episodes on the CURRENT environment"
    python scripts/collect_demos.py --task reach --episodes "$EPISODES" \
        --out "$DATA" --seed 0 2>&1 | tail -5
fi

# ---- 2. the manifest that L11 says has to exist -------------------------
python3 - <<PY
import json
import subprocess
from pathlib import Path

d = Path("$DATA")
commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                        text=True).stdout.strip()
dirty = bool(subprocess.run(["git", "status", "--porcelain", "src/", "scripts/"],
                            capture_output=True, text=True).stdout.strip())
n = len(list(d.glob("episode_*.npz")))
manifest = {
    "regenerate": f"python scripts/collect_demos.py --task reach "
                  f"--episodes $EPISODES --out {d} --seed 0",
    "env_commit": commit,
    "working_tree_dirty": dirty,
    "episodes": n,
    "collect_seed": 0,
    "note": "Written because ledger L11: the previous baseline's dataset was "
            "gitignored and regenerable in principle, which is not the same as "
            "regenerated. Without this the number is an anecdote.",
}
(d / "MANIFEST.json").write_text(json.dumps(manifest, indent=2))
print(f"manifest: {n} episodes, env {commit[:8]}"
      + ("  (WORKING TREE DIRTY -- not byte-reproducible)" if dirty else ""))
PY

# ---- 3. train both arms -------------------------------------------------
for s in $SEEDS; do
    ck="checkpoints/m2v2/bc_reach_seed${s}.pt"
    if [ -f "$ck" ]; then
        echo "### baseline seed $s already trained"
    else
        echo "### training baseline, seed $s"
        python scripts/train_bc.py --data "$DATA" --out checkpoints/m2v2 \
            --seed "$s" --epochs 50 2>&1 | grep -vE "UserWarning|self.blocks" | tail -2
        [ -f "checkpoints/m2v2/bc_seed${s}.pt" ] && mv "checkpoints/m2v2/bc_seed${s}.pt" "$ck"
    fi
done

# ---- 4. evaluate, with the leak check REQUIRED to pass ------------------
echo
echo "### evaluating -- the leak check must PASS, not skip"
python scripts/eval_policy.py --task reach \
    --checkpoints "checkpoints/m2v2/bc_reach_seed*.pt" \
    --train-data "$DATA" 2>&1 \
    | grep -aE "leak check|success" | tee logs/m2v2_eval.log

if grep -q "leak check: SKIPPED" logs/m2v2_eval.log; then
    echo
    echo "REFUSING THE NUMBER: the leak check skipped. That is exactly how the"
    echo "previous baseline became unverifiable. Fix --train-data and re-run."
    exit 1
fi
